//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thi64CNTTCLC2_64130758.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string AnhDaiDien { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<bool> NgonNgu { get; set; }
        public string TacGia { get; set; }
        public string MaLS { get; set; }
    
        public virtual LoaiSach LoaiSach { get; set; }
    }
}
